name: vtki-environment
channels:
  - bokeh/label/dev
  - pyviz/label/dev
dependencies:
  - python
  - bokeh
  - panel
  - pip
  - pip:
    - git+git://github.com/vtkiorg/vtki@master
    - matplotlib
    - git+git://github.com/OpenGeoVis/omfvtk@master
